package main

import (
	"fmt"
	"time"
)

func main() {
	span := time.Duration(666)
	fmt.Printf("%c[1;40;31m%s%c\n", 0x1B, "            ♥                ♥", 0x1B)
	time.Sleep(time.Millisecond * span)
	fmt.Printf("%c[1;40;31m%s%c\n", 0x1B, "        ♥       ♥      ♥       ♥", 0x1B)
	time.Sleep(time.Millisecond * span)
	fmt.Printf("%c[1;40;31m%s%c\n", 0x1B, "      ♥            ♥             ♥", 0x1B)
	time.Sleep(time.Millisecond * span)
	fmt.Printf("%c[1;40;31m%s%c\n", 0x1B, "     ♥                            ♥", 0x1B)
	time.Sleep(time.Millisecond * span)
	fmt.Printf("%c[1;40;31m%s%c\n", 0x1B, "      ♥                          ♥", 0x1B)
	time.Sleep(time.Millisecond * span)
	fmt.Printf("%c[1;40;31m%s%c\n", 0x1B, "         ♥                     ♥", 0x1B)
	time.Sleep(time.Millisecond * span)
	fmt.Printf("%c[1;40;31m%s%c\n", 0x1B, "            ♥               ♥", 0x1B)
	time.Sleep(time.Millisecond * span)
	fmt.Printf("%c[1;40;31m%s%c\n", 0x1B, "                ♥       ♥", 0x1B)
	time.Sleep(time.Millisecond * span)
	fmt.Printf("%c[1;40;31m%s%c\n", 0x1B, "                    ♥ ", 0x1B)
	time.Sleep(time.Second)
	fmt.Printf("%c[1;40;33m%s%c\n", 0x1B, "dont't leave, maybe a surprise is comming", 0x1B)
	time.Sleep(time.Second)
	fmt.Printf("%c[1;40;33m%s%c\n", 0x1B, "comming soon ~", 0x1B)
	time.Sleep(time.Second)
	fmt.Printf("%c[1;40;33m%s%c\n", 0x1B, "here it is~", 0x1B)
	time.Sleep(time.Second)
	fmt.Printf("%c[1;40;33m%s%c\n", 0x1B, "are you still waiting ?", 0x1B)
	time.Sleep(time.Second)
	fmt.Printf("%c[1;40;33m%s%c\n", 0x1B, "are you still waiting now ?", 0x1B)
	time.Sleep(time.Second)
	fmt.Printf("%c[1;40;33m%s%c\n", 0x1B, "and now ???", 0x1B)
	time.Sleep(time.Second)
	fmt.Printf("%c[1;40;33m%s%c\n", 0x1B, "good boy ", 0x1B)
	time.Sleep(time.Second)
	fmt.Printf("%c[1;40;33m%s%c\n", 0x1B, "oh man, you got to get some real thing to do", 0x1B)
	time.Sleep(time.Second)
	fmt.Printf("%c[1;40;33m%s%c\n", 0x1B, "do you believe there is a suprise ?", 0x1B)
	time.Sleep(time.Second)
	fmt.Printf("%c[1;40;33m%s%c\n", 0x1B, "do you believe there is a suprise ?", 0x1B)
	time.Sleep(time.Second)
	fmt.Printf("%c[1;40;33m%s%c\n", 0x1B, "do you believe there is a suprise ?", 0x1B)
	time.Sleep(time.Second)
	fmt.Printf("%c[1;40;33m%s%c\n", 0x1B, "for the sake of the time that you have waited ", 0x1B)
	time.Sleep(time.Second)
	fmt.Printf("%c[1;47;35m%s%c\n", 0x1B, "happy valentine's day and i love you ", 0x1B)
	fmt.Printf("%c[0m\n%c", 0x1B, 0x1B)
	time.Sleep(time.Second)
}
